# Generated by Django 5.2.5 on 2025-08-20 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memorials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeRoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_type', models.CharField(blank=True, max_length=50)),
                ('technical_requirements', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'WakeRoom Feature',
                'verbose_name_plural': 'WakeRoom Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WakeRoomExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_type', models.CharField(choices=[('AR', 'Augmented Reality'), ('VR', 'Virtual Reality'), ('360', '360° Video'), ('INTERACTIVE', 'Interactive Demo'), ('AUDIO', 'Spatial Audio')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='wakeroom/demos/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='wakeroom/thumbnails/')),
                ('ar_model_file', models.FileField(blank=True, null=True, upload_to='wakeroom/ar_models/')),
                ('vr_scene_file', models.FileField(blank=True, null=True, upload_to='wakeroom/vr_scenes/')),
                ('qr_code_required', models.BooleanField(default=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=500)),
                ('nfc_enabled', models.BooleanField(default=False)),
                ('nfc_data', models.CharField(blank=True, max_length=500)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('is_immersive', models.BooleanField(default=True)),
                ('requires_headset', models.BooleanField(default=False)),
                ('spatial_audio', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('associated_memorials', models.ManyToManyField(blank=True, related_name='wakeroom_experiences', to='memorials.memorial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WakeRoom Experience',
                'verbose_name_plural': 'WakeRoom Experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WakeRoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('interactions_count', models.PositiveIntegerField(default=0)),
                ('completed_milestones', models.JSONField(blank=True, default=list)),
                ('user_feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser_info', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wakeroom.wakeroomexperience')),
                ('memorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wakeroom_sessions', to='memorials.memorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wakeroom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WakeRoom Session',
                'verbose_name_plural': 'WakeRoom Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
