# Generated by Django 5.2.5 on 2025-08-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Birth & Childhood', 'Birth & Childhood'), ('Youth & Learning', 'Youth & Learning'), ('Love & Partnership', 'Love & Partnership'), ('Service & Achievement', 'Service & Achievement'), ('Wisdom & Legacy', 'Wisdom & Legacy')], max_length=100)),
                ('age_range', models.CharField(max_length=50)),
                ('icon_name', models.CharField(max_length=50)),
                ('color_class', models.CharField(max_length=100)),
                ('icon_color_class', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('milestones', models.JSONField(default=list)),
                ('spiritual_aspect', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Life Phase',
                'verbose_name_plural': 'Life Phases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline_stories/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='timeline_audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='timeline_video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('life_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='timeline.lifephase')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_stories', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Timeline Story',
                'verbose_name_plural': 'Timeline Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
