# Generated by Django 5.2.5 on 2025-08-20 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memorials/')),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim')], max_length=20)),
                ('categories', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('qr_code', models.BooleanField(default=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=500)),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('life_story', models.TextField(blank=True)),
                ('favorite_quotes', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'verbose_name': 'Memorial',
                'verbose_name_plural': 'Memorials',
                'ordering': ['-created_at'],
            },
        ),
    ]
