# Generated by Django 5.2.5 on 2025-08-20 21:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'License Feature',
                'verbose_name_plural': 'License Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('license_type', models.CharField(choices=[('FOMO_250', 'FOMO 250 Limited Edition'), ('STANDARD', 'Standard License'), ('PREMIUM', 'Premium License')], default='FOMO_250', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired')], default='available', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, default=2999.0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=1999.0, max_digits=10)),
                ('is_discounted', models.BooleanField(default=True)),
                ('discount_percentage', models.PositiveIntegerField(default=33, validators=[django.core.validators.MaxValueValidator(100)])),
                ('features', models.JSONField(default=list)),
                ('storage_limit_gb', models.PositiveIntegerField(default=1000)),
                ('family_members_limit', models.PositiveIntegerField(default=100)),
                ('lifetime_guarantee', models.BooleanField(default=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legacy License',
                'verbose_name_plural': 'Legacy Licenses',
                'ordering': ['license_number'],
            },
        ),
        migrations.CreateModel(
            name='LicensePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='legacy.legacylicense')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Purchase',
                'verbose_name_plural': 'License Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
